[app]
name = "Document Mapper"
version = "0.3"
description = "An application for mapping documents."
author = "Younes Rabeh"
organization = "YOUNIDEV"
domain = "younidev.com"

[logging]
persistence_logging = true

[window]
width = 800
height = 500
min_width = 800
min_height = 500
title = "Document Mapper"
theme_mode = "AUTO"

[resources]
base = "resources"
qss = "resources/qss"
icons = "resources/icons"
images = "resources/images"
fonts = "resources/fonts"
data = "resources/data"
temp = "resources/temp"
